### ISSUE TITLE
redirect from old content

### ISSUE THREAD

**Issue by benmccann** [sveltejs/svelte.dev#56]
The documentation URLs have changed significantly which will break links in tutorials, stackoverflow, etc. We should rename some of the content back to the old URLs or add redirects to send users to the corresponding new page.

See https://github.com/sveltejs/svelte/pull/12317 for an overview of which URLs have changed

**Comment by Leftium** [comment]
It would be nice if URL fragments from old links redirected to the specific section in new links.

For example in this tutorial there are two links: https://www.leftium.com/userfront-svelte/#userfront-environment-variables
- https://kit.svelte.dev/docs/modules#$env-static-private
- https://kit.svelte.dev/docs/modules#$env-static-public

It would be nice if they redirected to these links, instead of the base kit documentation
- https://svelte.dev/docs/kit/$env-static-private
- https://svelte.dev/docs/kit/$env-static-public
