### ISSUE TITLE
New site design looks really bad

### ISSUE THREAD

**Issue by Clonkex** [sveltejs/svelte.dev#660]
This is obviously subjective, but I feel strongly enough that I have to say it. It just looks plain bad. I honestly might not have decided to try Svelte if that had been my first impression. Even open-source products have to sell themselves. The [old homepage](https://web.archive.org/web/20240915010218/https://svelte.dev/) did this very well. Clean, slick, attractive, modern, puts some major selling points front and centre, and sports a snappy tagline. The new site... not so much. I don't want to just keep complaining, but to be completely honest I don't get why it was changed for Svelte 5. It's not like the new site even _advertises_ Svelte 5 (which any other framework would do - I would expect a banner across the top saying "Svelte 5 released!" at the very least). The impression I get now is that Svelte is a small-time, untested framework instead of the serious competitor to other major frameworks that it actually is.

There's a very good reason no one uses serif fonts for their _entire site_. Serif fonts are good for small accents (for instance, the `/'svelte/` pronunciation guide feature works great in serif). They do not look modern or clean. In fact, for several days after the new site launched, I thought the real fonts were just failing to load, because that's the only time I ever see serif fonts on a modern site (in fact, the whole site lacks any sense of cohesive styling; it almost feels like a plain HTML document rendering with stock browser styles). The font used for the body text (Georgia) is reasonably readable and not too bad (although it still doesn't exactly look good), but the heading font (DM Serif Display) is really, _really_ bad. It's so hard to read and does not look nice at all. Worst of all, the font toggle (because, yes, I eventually noticed there is one) only changes the body text (which has the more acceptable font), not the headings (which I still need to be able to quickly read, and which have the horrible font!).

I apologise for just hating on the site (and further apologise if this is insulting or offensive to the designers; remember this is only my opinion), but I'm simply baffled as to why such a huge backwards step was taken in the design. Feel free to ignore me, of course - it's your project, after all - but please at least take a look at any of the [other](https://react.dev) [major](https://nextjs.org) [frameworks'](https://vuejs.org) [websites](https://tailwindcss.com) ([I](https://preactjs.com) [can](https://emberjs.com) [keep](https://www.solidjs.com) [going](https://getbootstrap.com)) and compare.

**Comment by PixelSoftwareStudios** [comment]
Adding my two cents to this, I agree with your points almost entirely. 

On the font choice, it feels somewhat insulting to have the secondary font be "Atkinson Hyperlegible". While it's a great font and looks similar to the old font Overpass (which, in my opinion had a bit more charm and brand identity), if you look into the [description](https://fonts.google.com/specimen/Atkinson+Hyperlegible/about) of this font it is almost like you are saying anybody who dislikes the new font has something deficient about them. Honestly, with full sincerity, Comic Sans would have been a better choice. I almost refused to learn Svelte 5 because I got a migraine trying to read the new documentation before the font switcher was added. I was even considering writing a userscript just to make it legible. 

On the design front, what happened to the quickstart guide? I appreciated not having to scroll very far to see the commands I needed to create a project. On the Next.js website its one command right in the middle of the screen. Adding `npx sv create` somewhere immediately visible on the site with would really help users who didn't need the tutorial and just needed to quickly start a project. 

For example, for a period of time before the homepage had updated I was confused why create-svelte wasn't working because I was copying it straight from the website. Then when the site updated I was confused where the command was until I clicked through the get started tutorial and clicked "I'm brand new here". If I click "I’m migrating an app from Svelte 4" there is no mention of the new way to create projects, just migrating them. "If you’re already experienced with an older version of Svelte, the migration guide will bring you up to speed on the changes in Svelte 5." I believe a complete overhaul of the way you create projects is worth a mention at the top of the changes list for people who are migrating their understanding not just their current projects. Wouldn't be necessary if it was just on the front page.

The "Get started" button is also a little easy to overlook as the only obvious visual hierarchy technique used is color and an icon.

Where I disagree is I wouldn't say the old website was all that great. It had some strong points, but the new website has some great changes. For one, the new navbar is beautiful. One thing I would bring over from the old site is the list of corporate users. Some of the MASSIVE companies that were listed on the old site are missing. It would be nice to have all of them moving across the screen in a line like you see on most websites or just simply add another static line of them, unless they're no longer listed because they no longer use svelte. 

In the [blog post](https://svelte.dev/blog/the-omnisite) he does address some of these criticisms already and says himself this is controversial and that most will find it illegible and dated. He mentions that it’s less of an issue on high-resolution screens, I'd say my Retina XDR display is pretty sharp and my eyes felt offended. Why would you want people's first impressions to negative ("misguided" or not) on something that should be viewed as modern and the future of web dev. I also had the same reaction that I thought my fonts weren't loading and thought it looked unprofessional. He also mentions the site was cramped with "the five Bs", I don't think adding a little bit more visual hierarchy where it is needed would make it more cramped.

I don't believe serif fonts are all that bad, just these ones are particularly bad for this use case. I would even go as far to say this excessive usage is antithetical to the ethos "attractively thin, graceful and stylish".

**Comment by vladshcherbin** [comment]
[SvelteHack](https://hack.sveltesociety.dev/2024) is happening right now - it’s a great idea to submit a redesign and even win a prize for it 🥳

**Comment by moritzebeling** [comment]
Hey, since the redesign, the page somehow looks broken. As this is not a newspaper or poetry, I think sans and mono fonts are best suited for the topic of computer programming. I would be really thankful, if the original typography would be restored. Thank you

**Comment by Rich-Harris** [comment]
You're right, this is subjective.

> it’s a great idea to submit a redesign

This would be a waste of an entry.

**Comment by kvetoslavnovak** [comment]
Big thank for sans-serif font. This  helped a  lot. It was really hard to read serfi fonts, especially for people having some kind of "dis" reading problems. Very welcomed that now there is sans-serif version which is much more inclusive and accessible.
