### ISSUE TITLE
Playground flexbox remove trailing white-space CSS fix "white-space: pre-wrap" doesn't work

### ISSUE THREAD

**Issue by FirstProphet** [sveltejs/svelte.dev#667]
The following code when pasted into the Svelte 5 Playground doesn't work properly, i.e. the white-space between "one" and "two" isn't displayed. For reference you can paste it into jsfiddle.net or similar and see how it should work.
```html
<div id="container">
	<div id="one">one </div>
	<div id="two">two</div>
</div>

<style>
	#container {
		display: flex;
		white-space: pre-wrap;
	}
</style>
```

**Comment by Rich-Harris** [comment]
This isn't a playground issue, this is just how Svelte works — whitespace immediately inside blocks and elements is removed, because 99.9% of the time it's unwanted.

You have several options for the remaining 0.1%:

- use a `<pre>` element
- use `<svelte:options preserveWhitespace />` (applies to the entire component, or entire app if you set it as a global compiler option though you probably shouldn't — [demo](http://localhost:5173/playground/7ee42a5526864bd0b89388ca8bf728e8?version=5.1.9))
- `{' '}` ([demo](http://localhost:5173/playground/7ee42a5526864bd0b89388ca8bf728e8?version=5.1.9#H4sIAAAAAAAAE22PQQrCMBBFrxLGRTdV97EWPIdxEdsvBmISkrG1lN5dElFBXM77b2b4Mzl9A0kKEQlxgBivhpGC7kA1XYxFInmciaeQtQyofi8dQtikAZYzO-uEf7zzjuE4kaSmN4Mw_V4VqI1DVNQqp_ibeAdFrXeYK1EtzbY3w4_Bo1fU8ujf4UdyTeLJovirzwsx51lxb1KwepLiYvHYvVhpuy51pQgR6zHqULIl332do5oYDybJ8Y7ltDwBUwZ5izUBAAA=))

**Comment by FirstProphet** [comment]
Ah okay, I didn't realize flexbox in Svelte is supposed to behave differently than native css flexbox. 

`{' '}` is a neat trick tho

**Comment by Rich-Harris** [comment]
It's nothing to do with flexbox, it's to do with how markup is parsed
