### ISSUE TITLE
UX: The docs dropdown menu in navbar slows navigation

### ISSUE THREAD

**Issue by imdj** [sveltejs/svelte.dev#675]
Navigating to the docs should be one click away.
1. Docs are probably the most frequent destination. There shouldn't be any barriers.
2. There are only 2 options on the menu: Svelte and SvelteKit.

In general dropdown is clunky and a poor choice for navigating between the two top visited pages. Switching between Svelte and Kit docs should also be one click away at all times. 

## Possible solutions
1. Make the `Docs` link in the navbar leads directly to the svelte docs, with a link or section for SvelteKit.
2. Or, have both links directly in the navbar, `Docs` for svelte and another for SvelteKit.

**Comment by brunnerh** [comment]
Maybe go from:
![{DF931854-8AAC-4F5E-9758-FA2AE2910BB4}](https://github.com/user-attachments/assets/3000001c-4934-49e8-b828-e8d8a334eecc)

to:
![{DE6F753A-51FE-43F2-BA3D-9209EDFB5F5F}](https://github.com/user-attachments/assets/03eb5d33-480a-4897-a668-e9777855b93f)

**Comment by imdj** [comment]
@brunnerh I agree with unpacking the menu. The only nitpick I'd say about having `Svelte` and `SvelteKit` is that there are no hints that any lead to documentation. Which is why I see suggested renaming the Svelte one to `Docs` to help new users start somewhere.

**Comment by imdj** [comment]
I noticed the experience on mobile is is much better. The `docs` dropdown menu turn into a scrollable menu that include the docs of Svelte and SvelteKit in a table of content style. This is great. Obviously, this wouldn't work on desktop, but instead we could have the same thing on both but navigating to `/docs` instead and let that display the table of content. Why a scrollable menu on mobile, and a weird drop down on desktop, when you can scroll a page more naturally on both.

<details>
  <summary>View screenshot</summary>
  <p align="center">
      <img src="https://github.com/user-attachments/assets/de1fefa5-7d01-4279-947d-867b92980356" alt="Svelte.dev docs submenu on mobile" height="400">
  </p>
</details>

**Comment by dummdidumm** [comment]
There will be more entries within that dropdown soon, also hovering over it and then clicking on one seems really fast to me? I don't expect people to switch back and forth between the two all the time.

**Comment by imdj** [comment]
> hovering over it and then clicking on one seems really fast to me

It's not slow as in not responsive but a hot navigation path would ideally be click and done. Instead you've to hover to show menu, then move your mouse again to select before clicking the link finally.

> I don't expect people to switch back and forth between the two all the time

Currently at the top level of the navbar we've links to the blog and discord both more accessible than the docs which are in a dropdown menu behind hover.

In that light, the dropdown menu seemed like an unnecessary hurdle.

**Comment by Rich-Harris** [comment]
As @dummdidumm said we're going to be adding more entries to this in the near future, starting with the CLI. As such things will get very confusing if we start 'unpacking' things, because there won't be room for everything so we'd have to have a more convoluted tiered system.

> I noticed the experience on mobile is much better

On desktop you hover and immediately click (or tab twice and hit space). On mobile you tap to open a menu, tap to open _another_ menu, and then if you're looking for SvelteKit docs you have to scroll a long way before you can find them (I've been considering turning headings like `Docs • Svelte` into collapsible `<details>` blocks for that reason). I don't think the mobile navigation is _bad_ per se, but the claim that it's better than the desktop nav feels extremely odd.

Given our plans to add more stuff here, I'm going to go ahead and close this issue. If people still feel strongly when the menu is larger, we can potentially revisit in future but for now there's nothing to do.
